# Generated by Django 6.0.7 on 2026-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode_paiement',
            field=models.CharField(choices=[('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('sedad', 'Sedad'), ('especes', 'Espèces')], max_length=20),
        ),
    ]
