# Generated by Django 6.0.7 on 2026-08-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_payment_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('sedad', 'Sedad'), ('especes', 'Espèces')], default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
